services:
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      DBUSER: user
      DBPASS: password
      DBHOST: db
      DBNAME: mydb
    ports:
      - "8080:8080"
    networks:
      - app-network

  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


networks:
  app-network:
    driver: bridge