services:
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    environment:
      SECRET: byYimFGhO6c9/vi+aRMfU4F9jP9H1nZkOoVx93ybtN0= # move to AWS Secrets Manager
      DBUSER: user
      DBPASS: password
      DBHOST: db
      DBNAME: mydb
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  db-data: