sonar.projectKey=gkhnrsln_Simple-CRUD-Application
sonar.organization=gkhnrsln
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.language=go
sonar.exclusions=**/*.test.go,node_modules/**,dist/**